sudo: false
language: erlang
otp_release:
  - 18.3
  - 17.5
  - R16B02
  - R15B03

install:
  - wget https://s3.amazonaws.com/rebar3/rebar3 && chmod +x rebar3
  - export PATH="$TRAVIS_BUILD_DIR:$PATH"

script: rebar3 compile
